### ISSUE TITLE
Doesn't work (indexOf undefined)

### ISSUE THREAD

**Issue by Uter1007** [fsbahman/apidoc-swagger#22]
apidoc on it's own runs smoothly. 

apidoc-swagger -i dist/ -o doc/
(node:10252) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
warn: parser plugin 'param' not found in block: 0
error: Cannot read property 'indexOf' of undefined

**Comment by lzerma** [comment]
@Uter1007 try to use the excluding filters and remove the ***node_modules/*** folder.

**Comment by svanbelleghem** [comment]
Have the exact same problem.

apidoc-swagger -o/docs
warn: parser plugin 'param' not found in block: 1
error: Cannot read property 'indexOf' of undefined

Folderstructure:
![structuur-backend2](https://cloud.githubusercontent.com/assets/3299115/24092677/f6a6979e-0d4f-11e7-9758-cfcbafad7f1a.png)

Any idea how to resolve this?

**Comment by lzerma** [comment]
@svanbelleghem @Uter1007 Here try this: 

`apidoc-swagger -v -e "node_modules/" -f \'.*\\.js$\' -i ./api -o ./`

**Comment by svanbelleghem** [comment]
Btw: thanks for the reply ;)

`apidoc-swagger -v -e "node_modules/" -f \'.*\\.js$\' -i ./api -o ./`

```
verbose: apidoc-generator name: apidoc-swagger
verbose: apidoc-generator version: 0.2.2
verbose: apidoc-core version: 0.3.1
verbose: apidoc-spec version: 0.2.0
verbose: run parser
error: No files found.
{ Path: '.' }
```

**Comment by lzerma** [comment]
@svanbelleghem replace the `js` extension to which you are currently working with. 

`apidoc-swagger -v -e "node_modules/" -f \'.*\\.<replace me>$\' -i ./api -o ./`

**Comment by svanbelleghem** [comment]
> replace the js extension to which you are currently working with.

Do you mean the apidoc configfile which is written in json?

**Comment by lzerma** [comment]
What are the files that contain the documentation block on it? On the image that you attached I couldn't see any well-known structure for a project, so I need to know in order to help you out. 
`vendor` and `apidoc` doesn't mean nothing.

**Comment by svanbelleghem** [comment]
`vendor` is my composer output folder. `apidoc` is the output folder from a previous generated apidoc. Index.php contains the code that needs to be documented.

**Comment by lzerma** [comment]
@svanbelleghem ok, try this then `apidoc-swagger -v -e "node_modules/" -f \'.*\\.php$\' -i ./vendor/index.php -o ./`

**Comment by svanbelleghem** [comment]
Index.php is located on the root, not in vendor (excuses for the misunderstanding). But when I try `apidoc-swagger -v -e "node_modules/" -f \'.*\\.php$\' -i ./index.php -o ./` I still got the same result: 

`apidoc-swagger -v -e "node_modules/" -f \'.*\\.php$\' -i ./index.php -o ./`

`verbose: apidoc-generator name: apidoc-swagger
verbose: apidoc-generator version: 0.2.2
verbose: apidoc-core version: 0.3.1
verbose: apidoc-spec version: 0.2.0
verbose: run parser
error: No files found.
{ Path: '.' }`

**Comment by lzerma** [comment]
Ok, then try `cd /html/ && apidoc-swagger -v -e "node_modules/" -f \'.*\\.php$\' -i ./ -o ./`

If you still getting the same error, it means that it is not finding the `index.php`.

**Comment by svanbelleghem** [comment]
I'm really sorry but still getting the same error. But with cmd I can locate the file.

```
if exist index.php echo File Found!
File Found!
```

And when I run apidoc alone it runs smoothly. Do I need to specify some settings in apidoc.json or in my index.php besides the standart apidoc settings and annotations?

**Comment by svanbelleghem** [comment]
Ok, so for some reason this `apidoc-swagger -i example/ -o doc/` works perfectly!

**Comment by cyyeh** [comment]
@svanbelleghem `apidoc-swagger -i example/ -o doc/`, what files does the 'example' directory contain?

**Comment by RiceLinTW** [comment]
Same problem when run `apidoc-swagger`

Got these output
error: Cannot read property 'indexOf' of undefined
debug: TypeError: Cannot read property 'indexOf' of undefined
    at createFieldArrayDefinitions (/usr/local/lib/node_modules/apidoc-swagger/lib/apidocToSwagger.js:188:25)
    at createVerbDefinitions (/usr/local/lib/node_modules/apidoc-swagger/lib/apidocToSwagger.js:134:22)
    at createGetDeleteOutput (/usr/local/lib/node_modules/apidoc-swagger/lib/apidocToSwagger.js:236:29)
    at extractPaths (/usr/local/lib/node_modules/apidoc-swagger/lib/apidocToSwagger.js:64:19)
    at Object.toSwagger (/usr/local/lib/node_modules/apidoc-swagger/lib/apidocToSwagger.js:13:18)
    at Object.createApidocSwagger (/usr/local/lib/node_modules/apidoc-swagger/lib/index.js:107:63)
    at Object.<anonymous> (/usr/local/lib/node_modules/apidoc-swagger/bin/apidocSwagger.js:143:19)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)


Any update?

**Comment by Eamonnzhang** [comment]
still got the same error

**Comment by newsages** [comment]
Same

**Comment by BorisKotlyarov** [comment]
Open file `apidocToSwagger.js` row 274 
replace `if (verbs.parameter && verbs.parameter.fields.Parameter)` to 
`if (verbs.parameter && verbs.parameter && verbs.parameter.fields && verbs.parameter.fields.Parameter)`


![image](https://user-images.githubusercontent.com/17835383/88556146-58cc9980-d031-11ea-9089-4b8648a6d452.png)

see PR #57

**Comment by 18819296186** [comment]
I know why throw this error now~
Look at the photos.

 `var type = parameter.type;`
This  variant need to get the type, and this type from {}. But code lack the {}
> @apiParam {string} userId 用户

![image](https://user-images.githubusercontent.com/33246740/92561564-01b01a80-f2a7-11ea-81a5-a502b2cd36e7.png)

**Comment by aaaaaaaaaaalex** [comment]
@18819296186, you are right. In order to solve this problem:
Open file apidocToSwagger.js on row 190
replace
`var typeIndex = type.indexOf("[]");`
to
`var typeIndex = type === undefined ? -1 : type.indexOf("[]");`
