### ISSUE TITLE
apidoc-swagger needs to be updated to run with Node.js 12

### ISSUE THREAD

**Issue by datdinhquoc** [fsbahman/apidoc-swagger#40]
apidoc-swagger doesn't run on Node.js 12 any more, it complains something about 'primordials':

```
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/abix/.nvm/versions/node/v12.2.0/lib/node_modules/apidoc-swagger/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/abix/.nvm/versions/node/v12.2.0/lib/node_modules/apidoc-swagger/node_modules/natives/index.js:55:10)
    at Object. (/home/abix/.nvm/versions/node/v12.2.0/lib/node_modules/apidoc-swagger/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

**Comment by rusekr** [comment]
I'am got this error too

**Comment by rusekr** [comment]
i've tried to replace dependency of fs-extra with latest and error gone but result swagger.json became corrupt.

**Comment by fsbahman** [comment]
I've attempted before to update dependencies with recent versions, it was more work than expected, I need to find a time to fix it, if anyone could help will be nice.

**Comment by SaudTauqeer** [comment]
I can try to help with it. Any pointers for getting started?

**Comment by learningfun-dev** [comment]
@fsbahman Fixed this issue, can you please take a look at the PR
https://github.com/fsbahman/apidoc-swagger/pull/49

**Comment by fsbahman** [comment]
Thanks @kalramanoj2002 I will have a look.

**Comment by fsbahman** [comment]
New version v0.3.1 is released thanks to @kalramanoj2002, please check it out if issues are solved.

**Comment by rusekr** [comment]
have 1 error with 0.3.1: 
using old stable config (apidoc.json in root of project):
```
{
  "_comment": "REST API version",
  "version": "1.0.0",
  "sampleUrl": false,
  "title": "REST documentation",
  "header": {
    "title": "",
    "filename": "src/apidoc/header.md"
  },
  "footer": {
    "title": "",
    "filename": "src/apidoc/footer.md"
  }
}
```
Using this command in root of project:
```
npx apidoc-swagger -i src/rest/ -o built/public/doc-rest
```

Getting this error:
```
error: Can not read: src/apidoc/header.md.
```

Tried to use absulute path to file with no success. File exists and apidoc itself sees and uses it.

**Comment by learningfun-dev** [comment]
@fsbahman @rusekr  Fixed the header/footer issue. Can you please take a look
https://github.com/fsbahman/apidoc-swagger/pull/51

**Comment by rusekr** [comment]
> @fsbahman @rusekr Fixed the header/footer issue. Can you please take a look
> #51

Tested. Now error about header gone, but got new error:
```
# npx apidoc-swagger -i src/rest/ -o built/public/doc-rest
error: Empty parser result. 
{
  File: 'src/rest/project.js',
  Block: 1,
  Element: '@apiDescription',
  Source: '@apiDescription '
}
```

Where in `project.js` apiDescription is just empty:
```
  /**
   * @apiVersion 1.0.0
   * @apiPermission project.settings.get
   * @api {get} /project/settings Get project settings list
   * @apiDescription 
   * @apiName GetProjectSettings
   * @apiGroup ProjectSettings
```
Filled description and now it generates file without errors. Thanks!

**Comment by learningfun-dev** [comment]
@rusekr @fsbahman is  **apiDescription** an optional field? do we needs to handle the above scenario i.e. it should not throw error if **apiDescription** is empty or not provided?

**Comment by fsbahman** [comment]
I will spend some time later this week to see what is wrong, maybe PR from @rusekr  is good enough, I have to extent the unit test to find this issues as well.
Also  after upgrading some of the dependencies in this PR build is failing on CircleCi, look like some of the packages are not Linux compatible.

**Comment by rusekr** [comment]
Vote for 0.3.2 patch with patched headers. It can be used now with node 12 at all. Error with description is very minor for me. :)

**Comment by fsbahman** [comment]
Ok so for now I will just merge it and release new version. Thanks!

**Comment by fsbahman** [comment]
Done! v0.3.2
